version: "3.8"

services:
  backend:
    container_name: backend  # Nombre personalizado
    build:
      context: ./myapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    container_name: frontend  # Nombre personalizado
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
